(() => {
  'use strict';

  const $ = selector => document.querySelector(selector);
  const $$ = selector => [...document.querySelectorAll(selector)];
  const VERSION = '0.13';
  const GRID_MIN = 48;
  const GRID_MAX = 84;
  const MIN_PIANO = 36;
  const MAX_PIANO = 96;
  const BEATS = 64;
  const ROW_HEIGHT = 24;
  const COLORS = ['#b68cff', '#60c6a4', '#dfb658', '#dc7898', '#79b4e3'];
  const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
  const KEYBOARD_MAP = { a: 60, w: 61, s: 62, e: 63, d: 64, f: 65, t: 66, g: 67, y: 68, h: 69, u: 70, j: 71, k: 72 };
  const INSTRUMENTS = [['grand_piano','Grand Piano'],['soft_piano','Soft Piano'],['cello','Cello'],['strings','Strings'],['flute','Flute'],['horn','French Horn'],['choir','Choir'],['warm_pad','Warm Pad'],['bell','Bell'],['acoustic_guitar','Acoustic Guitar'],['electric_bass','Electric Bass'],['drum_kit','Drum Kit'],['retro_lead','Retro Lead'],['pluck','Pluck']];
  const SOUND_FONTS = {grand_piano:'acoustic_grand_piano',soft_piano:'acoustic_grand_piano',cello:'cello',strings:'string_ensemble_1',flute:'flute',horn:'french_horn',choir:'choir_aahs',warm_pad:'pad_2_warm',bell:'tubular_bells',acoustic_guitar:'acoustic_guitar_nylon',electric_bass:'electric_bass_finger',drum_kit:'synth_drum',retro_lead:'lead_1_square',pluck:'pizzicato_strings'};
  const SCALES = {'C major':{root:0,steps:[0,2,4,5,7,9,11]},'D minor':{root:2,steps:[0,2,3,5,7,8,10]},'A minor':{root:9,steps:[0,2,3,5,7,8,10]},'F major':{root:5,steps:[0,2,4,5,7,9,11]},'G major':{root:7,steps:[0,2,4,5,7,9,11]},'A♭ major':{root:8,steps:[0,2,4,5,7,9,11]}};
  const PRESETS = [['Coin','bright pickup'],['Magic Sparkle','shimmering charm'],['Laser','retro projectile'],['Jump','arcade rise'],['Portal','sweeping gate']];
  const POTION = {
    melody:'5,85,.5,72;5.5,85,1.5,72;7,84,1,72;8,84,1.5,72;9.5,84,.5,72;16,84,1,72;17,82,1,72;18,80,1,72;19,82,1,72;20,84,2,72;22,75,2,72;24,77,1,72;25,75,1,72;26,84,1,72;27,82,1,72;28,80,4,72;32,82,1,72;33,84,1,72;34,75,1,72;35,77,1,72;36,75,2,72;38,84,2,72;40,82,1,72;41,80,1,72;42,65,1,72;43,80,1,72;44,82,4,72;48,84,1,72;49,82,1,72;50,80,1,72;51,82,1,72;52,84,2,72;54,75,2,72;56,77,1,72;57,75,1,72;58,84,1,72;59,82,1,72;60,80,3,72',
    right:'0,65,2,66;0,72,2,66;0,80,2,66;2,80,.5,66;2.5,82,.5,66;3,84,.5,66;3.5,85,.5,66;4,61,2,66;4,68,2,66;4,73,2,66;4,77,2,66;6,61,2,66;6,68,2,66;6,77,2,66;6,85,2,66;8,61,2,66;8,68,2,66;8,77,2,66;8,85,2,66;10,61,1,66;10,68,1,66;10,84,1,66;11,63,1,66;11,68,1,66;11,75,1,66;12,65,2,66;12,72,2,66;12,80,2,66;14,65,2,66;14,80,2,66;14,84,2,66;16,65,2,66;16,68,2,66;16,84,2,66;18,63,2,66;18,68,2,66;18,82,2,66;20,61,2,66;20,68,2,66;20,73,2,66;20,77,2,66;22,65,2,66;22,68,2,66;22,84,2,66;24,63,2,66;24,68,2,66;24,75,2,66;26,61,2,66;26,68,2,66;26,84,2,66;28,65,4,66;28,68,4,66;28,84,4,66;32,65,2,66;32,70,2,66;32,82,2,66;34,72,2,66;34,75,2,66;34,77,2,66;36,63,2,66;36,75,2,66;36,82,2,66;38,65,2,66;38,68,2,66;38,84,2,66;40,61,2,66;40,65,2,66;40,68,2,66;42,65,2,66;42,68,2,66;42,84,2,66;44,63,4,66;44,67,4,66;44,82,4,66;48,65,2,66;48,68,2,66;48,84,2,66;50,63,2,66;50,68,2,66;50,82,2,66;52,61,2,66;52,68,2,66;52,73,2,66;52,77,2,66;54,65,2,66;54,68,2,66;54,84,2,66;56,63,2,66;56,68,2,66;56,75,2,66;58,61,2,66;58,68,2,66;58,84,2,66;60,65,3,66;60,68,3,66;60,84,3,66',
    left:'0,41,2,60;2,48,2,60;4,37,2,60;6,44,2,60;8,37,2,60;10,44,2,60;12,41,2,60;14,48,2,60;16,41,2,60;18,48,2,60;20,37,2,60;22,44,2,60;24,39,2,60;26,46,2,60;28,41,4,60;32,46,2,60;34,53,2,60;36,39,2,60;38,46,2,60;40,37,2,60;42,41,2,60;44,39,4,60;48,41,2,60;50,48,2,60;52,37,2,60;54,44,2,60;56,39,2,60;58,46,2,60;60,41,3,60'
  };

  const uid = () => `${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  const noteName = pitch => `${NOTE_NAMES[pitch % 12]}${Math.floor(pitch / 12)-1}`;
  const makeNote = (start,pitch,duration=1,velocity=92) => ({id:uid(),start,pitch,duration,velocity,instrument:null});
  const decode = (text,prefix) => text.split(';').map((row,index) => {const [start,pitch,duration,velocity]=row.split(',').map(Number);return {id:`${prefix}_${index}`,start,pitch,duration,velocity,instrument:null};});

  function blankProject() {
    return {title:'Untitled cue',bpm:92,key:'D minor',sections:[],tracks:[{id:uid(),name:'Piano',instrument:'grand_piano',color:COLORS[0],muted:false,solo:false,notes:[]}]};
  }
  function potionProject() {
    return {title:'Potion Song — Piano Example',bpm:120,key:'A♭ major',source:{filename:'potion_song_all_piano_v7.mid',durationSeconds:31.5,embeddedKeySignature:null,embeddedTimeSignature:null},sections:[{id:uid(),name:'Bars 1–4',start:0,end:16,color:COLORS[2]},{id:uid(),name:'Bars 5–8',start:16,end:32,color:COLORS[0]},{id:uid(),name:'Bars 9–12',start:32,end:48,color:COLORS[1]},{id:uid(),name:'Bars 13–16',start:48,end:64,color:COLORS[3]}],tracks:[{id:uid(),name:'Melody guide',instrument:'grand_piano',color:COLORS[0],muted:false,solo:false,notes:decode(POTION.melody,'guide')},{id:uid(),name:'Piano right',instrument:'grand_piano',color:COLORS[1],muted:false,solo:false,notes:decode(POTION.right,'right')},{id:uid(),name:'Piano left',instrument:'grand_piano',color:COLORS[2],muted:false,solo:false,notes:decode(POTION.left,'left')}]};
  }
  function normalise(raw) {
    const fallback=blankProject();
    if(!raw||!Array.isArray(raw.tracks)||!raw.tracks.length)return fallback;
    return {...fallback,...raw,tracks:raw.tracks.map((track,i)=>({...fallback.tracks[0],...track,id:track.id||uid(),color:track.color||COLORS[i%COLORS.length],muted:Boolean(track.muted),solo:Boolean(track.solo),notes:Array.isArray(track.notes)?track.notes.map(note=>({...makeNote(0,60),...note,id:note.id||uid()})):[]})),sections:Array.isArray(raw.sections)?raw.sections.map((section,i)=>({id:section.id||uid(),name:section.name||`Section ${i+1}`,start:Number(section.start)||0,end:Number(section.end)||8,color:section.color||COLORS[i%COLORS.length]})):[]};
  }

  let project;
  try{project=normalise(JSON.parse(localStorage.getItem('ihy-v013')||localStorage.getItem('ihy-v012')||localStorage.getItem('ihy-v011')||localStorage.getItem('ihy-v009')||'null'));}catch(_){project=blankProject();}
  let activeTrackId=project.tracks[0].id,beatWidth=40,selected=null,noteDrag=null,noteMenuRef=null,timelineDragging=false,playheadBeat=0,isPlaying=false,playbackStartedAt=0,playbackStartBeat=0,animationFrame=0,pressed=new Set(),recording=false,recordStartedAt=0,metronome=false,chordMode=localStorage.getItem('ihy-chord-mode')==='true',pendingAction=null,savedSnapshot='';
  let context=null,master=null,playbackToken=0;const players=new Map(),loads=new Map(),stops=[],timers=[];
  const getTrack=id=>project.tracks.find(track=>track.id===id);
  const instName=id=>(INSTRUMENTS.find(item=>item[0]===id)||[id,id])[1];
  const secBeat=()=>60/Math.max(30,Number(project.bpm)||92);
  const snap=v=>{const unit=Number($('#quant').value||.25);return Math.round(v/unit)*unit;};

  function updateProjectMeta(){project.title=$('#title').value||project.title;project.bpm=Number($('#bpm').value)||92;project.key=$('#key').value;}
  function snapshot(){updateProjectMeta();return JSON.stringify(project);}
  function setStatus(message,timeout=3300){$('#status').textContent=message;clearTimeout(setStatus.timer);if(timeout)setStatus.timer=setTimeout(()=>{$('#status').textContent='v0.13 — direct composition workspace.';},timeout);}
  function setView(view){$$('.view').forEach(item=>item.classList.toggle('active',item.id===`${view}View`));}
  function ensureAudio(){if(context){if(context.state==='suspended')context.resume().catch(()=>{});return context;}const API=window.AudioContext||window.webkitAudioContext;if(!API)return null;context=new API();master=context.createGain();master.gain.value=.72;master.connect(context.destination);return context;}
  async function loadInstrument(id){if(!window.Soundfont||!SOUND_FONTS[id])return null;if(players.has(id))return players.get(id);if(loads.has(id))return loads.get(id);const audio=ensureAudio();if(!audio)return null;const loading=window.Soundfont.instrument(audio,SOUND_FONTS[id],{soundfont:'MusyngKite',format:'mp3',destination:master,gain:.9}).then(player=>{players.set(id,player);loads.delete(id);return player;}).catch(()=>{loads.delete(id);setStatus(`${instName(id)} samples could not load — synth fallback active.`,6000);return null;});loads.set(id,loading);return loading;}
  function synth(id,midi,velocity,duration,when){const audio=ensureAudio();if(!audio)return;const amount=clamp((velocity||92)/127,.08,1);const output=audio.createGain(),osc=audio.createOscillator();let wave='triangle',hz=440*Math.pow(2,(midi-69)/12);if(id==='retro_lead'||id==='drum_kit')wave='square';if(id==='drum_kit'){hz=120;duration=.12;}if(id==='cello'||id==='horn')wave='sawtooth';if(id==='bell'||id==='flute'||id==='warm_pad'||id==='choir')wave='sine';osc.type=wave;osc.frequency.setValueAtTime(hz,when);output.gain.setValueAtTime(.0001,when);output.gain.exponentialRampToValueAtTime(.11*amount,when+.012);output.gain.exponentialRampToValueAtTime(.0001,when+Math.max(.08,duration));osc.connect(output).connect(master);osc.start(when);osc.stop(when+Math.max(.08,duration)+.07);stops.push(()=>{try{osc.stop();osc.disconnect();output.disconnect();}catch(_){}});}
  function sample(player,midi,velocity,duration,when){try{const node=player.play(midi,when,{duration:Math.max(.08,duration),gain:clamp((velocity||92)/127,.12,.96),attack:.005,release:Math.min(.35,Math.max(.08,duration*.35))});if(node?.stop)stops.push(()=>{try{node.stop();}catch(_){}});return true;}catch(_){return false;}}
  function glow(midi,on){const key=document.querySelector(`.key[data-pitch="${midi}"]`);if(!key)return;const count=Math.max(0,Number(key.dataset.glow||0)+(on?1:-1));key.dataset.glow=count;key.classList.toggle('playing',count>0);}
  function scheduleGlow(midi,delay,duration){const a=setTimeout(()=>{glow(midi,true);const b=setTimeout(()=>glow(midi,false),Math.max(90,duration));timers.push(b);},Math.max(0,delay));timers.push(a);}
  function clearGlows(){$$('.key.playing').forEach(key=>{key.classList.remove('playing');key.dataset.glow='0';});}
  function setPlayhead(beat,follow=false){playheadBeat=clamp(beat,0,BEATS);const left=`${playheadBeat*beatWidth}px`;const grid=$('#playhead'),arr=$('#arrangementPlayhead');if(grid)grid.style.left=left;if(arr)arr.style.left=left;if(follow){const scroll=$('#rollScroll'),target=playheadBeat*beatWidth;if(target>scroll.scrollLeft+scroll.clientWidth-120)scroll.scrollLeft=Math.max(0,target-scroll.clientWidth*.35);}}
  function stopPlayback(reset=false){playbackToken++;timers.splice(0).forEach(clearTimeout);stops.splice(0).forEach(stop=>stop());if(animationFrame)cancelAnimationFrame(animationFrame);animationFrame=0;isPlaying=false;clearGlows();if(reset)setPlayhead(0);}
  function animate(){if(!isPlaying)return;const beat=playbackStartBeat+((performance.now()-playbackStartedAt)/1000)/secBeat();if(beat>=BEATS){stopPlayback(true);setStatus('Playback reached the end.');return;}setPlayhead(beat,true);animationFrame=requestAnimationFrame(animate);}
  async function playProject(){closeNoteMenu();stopPlayback(false);const token=++playbackToken,soloed=project.tracks.some(track=>track.solo),activeTracks=project.tracks.filter(track=>!track.muted&&(!soloed||track.solo)),ids=[...new Set(activeTracks.flatMap(track=>[track.instrument,...track.notes.map(note=>note.instrument).filter(Boolean)]))],missing=ids.filter(id=>SOUND_FONTS[id]&&!players.has(id));if(missing.length)setStatus(`Loading sampled ${missing.map(instName).join(', ')}…`,0);await Promise.all(ids.map(loadInstrument));if(token!==playbackToken)return;const audio=ensureAudio();if(!audio)return;const now=audio.currentTime+.08,start=playheadBeat,beatSeconds=secBeat();for(const track of activeTracks){for(const note of track.notes){const end=note.start+note.duration;if(end<=start)continue;const actualStart=Math.max(start,note.start),duration=end-actualStart,delay=(actualStart-start)*beatSeconds,id=note.instrument||track.instrument,pitch=clamp(note.pitch+Number($('#transpose').value||0),MIN_PIANO,MAX_PIANO),player=players.get(id);if(player)sample(player,pitch,note.velocity,duration*beatSeconds,now+delay);else synth(id,pitch,note.velocity,duration*beatSeconds,now+delay);scheduleGlow(pitch,delay*1000,duration*beatSeconds*1000);}}
    if(metronome){const bell=players.get('bell');for(let beat=Math.ceil(start);beat<BEATS;beat++){const delay=(beat-start)*beatSeconds,pitch=beat%4===0?84:76;if(bell)sample(bell,pitch,52,.06,now+delay);else synth('bell',pitch,52,.06,now+delay);}}
    isPlaying=true;playbackStartBeat=start;playbackStartedAt=performance.now()+80;animationFrame=requestAnimationFrame(animate);setStatus(`Playing from beat ${start.toFixed(2)}.`);}
  async function playImmediate(midi,beats=.5){const track=getTrack(activeTrackId),id=track.instrument,pitch=clamp(midi+Number($('#transpose').value||0),MIN_PIANO,MAX_PIANO),duration=beats*secBeat(),audio=ensureAudio();if(!audio)return;if(!players.has(id)&&SOUND_FONTS[id])setStatus(`Loading ${instName(id)} samples…`,0);const player=await loadInstrument(id),now=audio.currentTime+.02;if(player)sample(player,pitch,96,duration,now);else synth(id,pitch,96,duration,now);scheduleGlow(pitch,20,duration*1000);}

  function isInScale(pitch,scale){return scale.steps.includes(((pitch-scale.root)%12+12)%12);}
  function closestScalePitch(pitch,scale){let best=pitch,bestDistance=Infinity;for(let delta=-6;delta<=6;delta++){const trial=pitch+delta;if(trial<GRID_MIN||trial>GRID_MAX||!isInScale(trial,scale))continue;if(Math.abs(delta)<bestDistance){best=trial;bestDistance=Math.abs(delta);}}return best;}
  function diatonicAbove(pitch,steps,scale){let candidate=pitch,remaining=steps;while(remaining>0){candidate++;if(isInScale(candidate,scale))remaining--;}return candidate;}
  function chordFor(pitch){const scale=SCALES[$('#key').value]||SCALES['D minor'];let root=closestScalePitch(pitch,scale),third=diatonicAbove(root,2,scale),fifth=diatonicAbove(root,4,scale);while(fifth>GRID_MAX&&root-12>=GRID_MIN){root-=12;third=diatonicAbove(root,2,scale);fifth=diatonicAbove(root,4,scale);}return [root,third,fifth].filter(value=>value>=GRID_MIN&&value<=GRID_MAX);}
  function renderChord(){const button=$('#chordToggle');button.classList.toggle('on',chordMode);button.setAttribute('aria-pressed',String(chordMode));button.title=chordMode?`${$('#key').value}: key-aware triads on`:'Add one note per click';}
  function renderTracks(){const root=$('#tracks'),armed=$('#armed');root.innerHTML='';armed.innerHTML='';for(const track of project.tracks){armed.insertAdjacentHTML('beforeend',`<option value="${track.id}" ${track.id===activeTrackId?'selected':''}>${track.name}</option>`);root.insertAdjacentHTML('beforeend',`<div class="track ${track.id===activeTrackId?'active':''}"><span class="swatch" style="background:${track.color}"></span><button class="btn" data-arm="${track.id}">${track.name}</button><span class="instrument">${instName(track.instrument)}</span><span><button class="btn" data-mute="${track.id}">M</button><button class="btn" data-solo="${track.id}">S</button></span></div>`);}$('#instrument').innerHTML=INSTRUMENTS.map(item=>`<option value="${item[0]}">${item[1]}</option>`).join('');$('#instrument').value=getTrack(activeTrackId).instrument;}
  function renderArrangement(){const root=$('#arrangement');root.innerHTML='<div class="arrangement-playhead" id="arrangementPlayhead"></div>';root.style.width=`${BEATS*beatWidth}px`;for(let beat=0;beat<=BEATS;beat+=4)root.insertAdjacentHTML('beforeend',`<span class="ruler-mark" style="left:${beat*beatWidth+4}px">${beat/4+1}</span>`);for(const section of project.sections)root.insertAdjacentHTML('beforeend',`<button class="arrangement-section" data-section="${section.id}" style="left:${section.start*beatWidth+4}px;width:${Math.max(38,(section.end-section.start)*beatWidth-8)}px;background:${section.color}">${section.name}</button>`);}
  function renderRoll(){const labels=$('#labels'),roll=$('#roll');labels.innerHTML='';roll.innerHTML='<div class="playhead" id="playhead"></div>';roll.style.width=`${BEATS*beatWidth}px`;for(let pitch=GRID_MAX;pitch>=GRID_MIN;pitch--)labels.insertAdjacentHTML('beforeend',`<div class="pitch-label ${pitch%12===0?'c':''}">${noteName(pitch)}</div>`);for(let beat=0;beat<=BEATS;beat+=4)roll.insertAdjacentHTML('beforeend',`<span class="bar" style="left:${beat*beatWidth+4}px">${beat/4+1}</span>`);for(const track of project.tracks)for(const note of track.notes)roll.insertAdjacentHTML('beforeend',`<div class="note ${selected?.note.id===note.id?'selected':''}" data-note="${note.id}" title="${track.name} · ${noteName(note.pitch)} · ${note.duration} beats" style="left:${note.start*beatWidth+1}px;top:${(GRID_MAX-note.pitch)*ROW_HEIGHT+2}px;width:${Math.max(10,note.duration*beatWidth-2)}px;background:${track.color}"><span class="resize"></span></div>`);setPlayhead(playheadBeat);}
  function renderKeyboard(){const piano=$('#piano');piano.innerHTML='';const whites=[];for(let pitch=MIN_PIANO;pitch<=MAX_PIANO;pitch++)if(![1,3,6,8,10].includes(pitch%12))whites.push(pitch);for(const pitch of whites){const mapped=Object.entries(KEYBOARD_MAP).find(([,value])=>value===pitch)?.[0]?.toUpperCase()||'';piano.insertAdjacentHTML('beforeend',`<button class="key" data-pitch="${pitch}">${noteName(pitch)}${mapped}</button>`);}for(let pitch=MIN_PIANO;pitch<=MAX_PIANO;pitch++)if([1,3,6,8,10].includes(pitch%12))piano.insertAdjacentHTML('beforeend',`<button class="key black" data-pitch="${pitch}" style="left:${9+whites.indexOf(pitch-1)*44+30}px">${noteName(pitch)}</button>`);}
  function renderPresets(){const root=$('#presets');if(root)root.innerHTML=PRESETS.map((preset,index)=>`<button class="preset" data-preset="${index}"><b>${preset[0]}</b><span>${preset[1]}</span></button>`).join('');}
  function render(){updateProjectMeta();renderTracks();renderArrangement();renderRoll();renderKeyboard();renderPresets();renderChord();}
  function findNote(id){for(const track of project.tracks){const note=track.notes.find(item=>item.id===id);if(note)return {track,note};}return null;}
  function createAt(event){const rect=$('#roll').getBoundingClientRect(),start=snap(clamp((event.clientX-rect.left)/beatWidth,0,BEATS-.125)),clicked=clamp(GRID_MAX-Math.floor((event.clientY-rect.top)/ROW_HEIGHT),GRID_MIN,GRID_MAX),track=getTrack(activeTrackId),pitches=chordMode?chordFor(clicked):[clicked],notes=pitches.map(pitch=>makeNote(start,pitch));track.notes.push(...notes);selected={track,note:notes[0]};renderRoll();setStatus(chordMode?`Added ${$('#key').value} triad to ${track.name}.`:`Added ${noteName(clicked)} to ${track.name}.`);}
  function closeNoteMenu(){$('#notePopover').hidden=true;noteMenuRef=null;}
  function openNoteMenu(ref,event){noteMenuRef=ref;const menu=$('#notePopover');$('#notePopoverTitle').textContent=`${ref.track.name} · ${noteName(ref.note.pitch)}`;$('#noteMenuInstrument').innerHTML=`<option value="">Track instrument — ${instName(ref.track.instrument)}</option>`+INSTRUMENTS.map(item=>`<option value="${item[0]}">${item[1]}</option>`).join('');$('#noteMenuInstrument').value=ref.note.instrument||'';$('#noteMenuVelocity').value=ref.note.velocity||92;$('#noteMenuLength').value=ref.note.duration;menu.hidden=false;menu.style.left=`${Math.min(event.clientX,window.innerWidth-menu.offsetWidth-8)}px`;menu.style.top=`${Math.min(event.clientY,window.innerHeight-menu.offsetHeight-8)}px`;}
  function applyNoteMenu(){if(!noteMenuRef)return;const note=noteMenuRef.note;note.instrument=$('#noteMenuInstrument').value||null;note.velocity=clamp(Number($('#noteMenuVelocity').value)||92,1,127);note.duration=clamp(snap(Number($('#noteMenuLength').value)||1),.125,BEATS-note.start);selected=noteMenuRef;closeNoteMenu();renderRoll();setStatus('Note updated.');}
  function deleteNote(){if(!noteMenuRef)return;noteMenuRef.track.notes=noteMenuRef.track.notes.filter(note=>note.id!==noteMenuRef.note.id);selected=null;closeNoteMenu();renderRoll();setStatus('Note deleted.');}
  function saveProject(silent=false){updateProjectMeta();localStorage.setItem('ihy-v013',JSON.stringify(project));savedSnapshot=snapshot();if(!silent)setStatus(`Saved “${project.title}” locally.`);}
  function exportProject(){saveProject(true);const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`${(project.title||'ihy-project').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.ihy.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Exported editable Ihy JSON.');}
  function importProject(file){const reader=new FileReader();reader.onload=()=>{try{project=normalise(JSON.parse(String(reader.result)));activeTrackId=project.tracks[0].id;playheadBeat=0;$('#title').value=project.title;$('#bpm').value=project.bpm;$('#key').value=project.key;render();savedSnapshot='';setStatus(`Imported “${project.title}”. Save it locally when ready.`);}catch(error){alert(`Invalid Ihy JSON: ${error.message}`);}};reader.readAsText(file);}
  function openProjectDialog(title,message,action){pendingAction=action;$('#projectDialogTitle').textContent=title;$('#projectDialogText').textContent=message;$('#projectDialogBackdrop').hidden=false;}
  function requestReplace(title,message,action){if(snapshot()!==savedSnapshot){openProjectDialog(title,message,action);return;}action();}
  function runReplacement(saveFirst){const action=pendingAction;$('#projectDialogBackdrop').hidden=true;pendingAction=null;if(saveFirst)saveProject(true);if(action)action();}
  function newComposition(){requestReplace('Start a new blank composition?','Your current composition will be replaced. Would you like to save it first?',()=>{project=blankProject();activeTrackId=project.tracks[0].id;playheadBeat=0;$('#title').value=project.title;$('#bpm').value=project.bpm;$('#key').value=project.key;selected=null;render();savedSnapshot='';setView('compose');setStatus('New blank composition ready.');});}
  function loadExample(){requestReplace('Load Potion Song example?','Your current composition will be replaced by the imported piano example. Would you like to save it first?',()=>{project=potionProject();activeTrackId=project.tracks[0].id;playheadBeat=0;$('#title').value=project.title;$('#bpm').value=project.bpm;$('#key').value=project.key;selected=null;render();savedSnapshot='';setView('compose');setStatus('Loaded Potion Song — Piano Example.');});}
  function arrangementBeat(event){const rect=$('#arrangement').getBoundingClientRect();return clamp((event.clientX-rect.left)/beatWidth,0,BEATS);}

  $('#newProject').addEventListener('click',newComposition);$('#save').addEventListener('click',()=>saveProject(false));$('#loadExample').addEventListener('click',loadExample);$('#createSound').addEventListener('click',()=>setView('create'));$('#libraryButton').addEventListener('click',()=>setView('library'));$('#analyseButton').addEventListener('click',()=>setView('analyse'));$('#signalButton').addEventListener('click',()=>setView('signal'));$('#import').addEventListener('click',()=>$('#file').click());$('#export').addEventListener('click',exportProject);$('#file').addEventListener('change',event=>{if(event.target.files[0])importProject(event.target.files[0]);event.target.value='';});
  $('#dialogSave').addEventListener('click',()=>runReplacement(true));$('#dialogDiscard').addEventListener('click',()=>runReplacement(false));$('#dialogCancel').addEventListener('click',()=>{$('#projectDialogBackdrop').hidden=true;pendingAction=null;});
  $('#chordToggle').addEventListener('click',()=>{chordMode=!chordMode;localStorage.setItem('ihy-chord-mode',String(chordMode));renderChord();setStatus(chordMode?`Chord mode on — ${$('#key').value} triads.`:'Chord mode off — clicks add one note.');});
  $('#key').addEventListener('change',()=>{project.key=$('#key').value;renderChord();});
  $('#armed').addEventListener('change',event=>{activeTrackId=event.target.value;selected=null;closeNoteMenu();renderTracks();renderRoll();});
  $('#transpose').addEventListener('change',()=>{});$('#quant').addEventListener('change',()=>{});
  $('#tracks').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.arm){activeTrackId=button.dataset.arm;selected=null;closeNoteMenu();renderTracks();renderRoll();}if(button.dataset.mute){const track=getTrack(button.dataset.mute);track.muted=!track.muted;renderTracks();}if(button.dataset.solo){const track=getTrack(button.dataset.solo);track.solo=!track.solo;renderTracks();}});
  $('#addTrack').addEventListener('click',()=>{const track={id:uid(),name:`Track ${project.tracks.length+1}`,instrument:'grand_piano',color:COLORS[project.tracks.length%COLORS.length],muted:false,solo:false,notes:[]};project.tracks.push(track);activeTrackId=track.id;render();});
  $('#addSection').addEventListener('click',()=>{const name=prompt('Section name','New section');if(!name?.trim())return;const last=project.sections.at(-1),start=last?clamp(last.end,0,BEATS-4):0;project.sections.push({id:uid(),name:name.trim(),start,end:Math.min(BEATS,start+8),color:COLORS[project.sections.length%COLORS.length]});renderArrangement();});
  $('#arrangement').addEventListener('click',event=>{const button=event.target.closest('.arrangement-section');if(!button)return;const section=project.sections.find(item=>item.id===button.dataset.section),name=prompt('Section name',section.name);if(name?.trim()){section.name=name.trim();renderArrangement();}});
  $('#clear').addEventListener('click',()=>{const track=getTrack(activeTrackId);if(confirm(`Clear all notes from ${track.name}?`)){track.notes=[];selected=null;closeNoteMenu();renderRoll();}});
  $('#roll').addEventListener('pointerdown',event=>{if(event.button!==0)return;const element=event.target.closest('.note');if(!element){if(event.target.id==='roll'){closeNoteMenu();createAt(event);}return;}const ref=findNote(element.dataset.note);if(!ref)return;event.preventDefault();selected=ref;noteDrag={ref,mode:event.target.classList.contains('resize')?'resize':'move',x:event.clientX,y:event.clientY,start:ref.note.start,pitch:ref.note.pitch,duration:ref.note.duration};renderRoll();});
  $('#roll').addEventListener('pointermove',event=>{if(!noteDrag)return;const dx=(event.clientX-noteDrag.x)/beatWidth,dy=Math.round((event.clientY-noteDrag.y)/ROW_HEIGHT);if(noteDrag.mode==='resize')noteDrag.ref.note.duration=clamp(snap(noteDrag.duration+dx),.125,BEATS-noteDrag.ref.note.start);else{noteDrag.ref.note.start=clamp(snap(noteDrag.start+dx),0,BEATS-noteDrag.ref.note.duration);noteDrag.ref.note.pitch=clamp(noteDrag.pitch-dy,GRID_MIN,GRID_MAX);}renderRoll();});
  ['pointerup','pointercancel'].forEach(type=>$('#roll').addEventListener(type,()=>{noteDrag=null;}));
  $('#roll').addEventListener('contextmenu',event=>{const element=event.target.closest('.note');if(!element)return;event.preventDefault();const ref=findNote(element.dataset.note);if(ref)openNoteMenu(ref,event);});
  $('#noteMenuApply').addEventListener('click',applyNoteMenu);$('#noteMenuDelete').addEventListener('click',deleteNote);$('#noteMenuClose').addEventListener('click',closeNoteMenu);document.addEventListener('pointerdown',event=>{const menu=$('#notePopover');if(!menu.hidden&&!menu.contains(event.target)&&!event.target.closest('.note'))closeNoteMenu();});
  $('#rollScroll').addEventListener('scroll',()=>{$('#arrangementViewport').scrollLeft=$('#rollScroll').scrollLeft;});
  $('#arrangement').addEventListener('pointerdown',event=>{timelineDragging=true;setPlayhead(arrangementBeat(event));});$('#arrangement').addEventListener('pointermove',event=>{if(timelineDragging)setPlayhead(arrangementBeat(event));});['pointerup','pointercancel'].forEach(type=>$('#arrangement').addEventListener(type,()=>{timelineDragging=false;}));
  $('#piano').addEventListener('pointerdown',event=>{const key=event.target.closest('.key');if(key)playImmediate(Number(key.dataset.pitch),pressed.has(' ')?1.35:.5);});
  $('#record').addEventListener('click',()=>{recording=!recording;recordStartedAt=performance.now();$('#record').classList.toggle('on',recording);$('#record').textContent=recording?'⏺ Recording':'⏺ Record';setStatus(recording?'Recording keyboard notes.':'Recording stopped.');});
  $('#metro').addEventListener('click',()=>{metronome=!metronome;$('#metro').classList.toggle('on',metronome);setStatus(metronome?'Metronome enabled.':'Metronome disabled.');});$('#play').addEventListener('click',playProject);$('#stop').addEventListener('click',()=>{stopPlayback(false);setStatus('Playback stopped.');});
  $('#presets').addEventListener('click',event=>{const button=event.target.closest('[data-preset]');if(!button)return;const [name]=PRESETS[Number(button.dataset.preset)];const audio=ensureAudio();if(audio)synth('retro_lead',69,96,.28,audio.currentTime);setStatus(`${name} synth preset previewed.`);});
  document.addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(event.code==='Space'){event.preventDefault();pressed.add(' ');return;}const key=event.key.toLowerCase();if(!KEYBOARD_MAP[key]||pressed.has(key))return;pressed.add(key);const duration=pressed.has(' ')?1.35:.5;playImmediate(KEYBOARD_MAP[key],duration);if(recording){const start=snap(((performance.now()-recordStartedAt)/1000)/secBeat());if(start<BEATS){const note=makeNote(start,KEYBOARD_MAP[key],duration);getTrack(activeTrackId).notes.push(note);selected={track:getTrack(activeTrackId),note};renderRoll();}}});document.addEventListener('keyup',event=>{if(event.code==='Space')pressed.delete(' ');else pressed.delete(event.key.toLowerCase());});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeNoteMenu();});window.addEventListener('pagehide',()=>stopPlayback(false));
  $('#title').value=project.title;$('#bpm').value=project.bpm;$('#key').value=project.key;render();savedSnapshot=snapshot();
})();