(() => {
    'use strict';

    const $ = (id) => document.getElementById(id);
    const els = {
        topPanel: $('top-panel'), countdown: $('countdown-circle'), imagePicker: $('image-picker'), videoPicker: $('video-picker'),
        frameGrid: $('frame-grid'), queueCard: $('queue-card'), compileBtn: $('compile-btn'), zipBtn: $('zip-btn'), openEditorBtn: $('open-editor-btn'),
        outputCard: $('output-card'), viewport: $('compiled-viewport'), downloadAnchor: $('download-anchor'),
        previewModal: $('preview-modal'), previewImg: $('modal-img'), animModal: $('anim-preview-modal'), animImg: $('anim-modal-img'), animLoading: $('anim-loading'),
        alignModal: $('align-modal'), alignCanvas: $('align-canvas'), editorModal: $('frame-editor-modal'), editorWindow: $('editor-window'), editorCanvas: $('frame-editor-canvas'), canvasViewport: $('canvas-viewport')
    };

    const state = {
        frames: [], cutoutActions: [], paintActions: [], movingActions: [], fixedBaseEnabled: false, baseFrameIndex: 0,
        currentPreviewIndex: null, alignIndex: 0, editorIndex: 0, editorPlaying: false, editorTimer: null,
        animationTimer: null, animationPlaying: false, history: [], historyIndex: -1
    };
    const edit = {
        tool: 'rect', target: 'cutout', maskMode: 'remove', paintMode: 'paint', movingMode: 'add', finalView: true,
        zoom: 1, panX: 0, panY: 0, drawing: false, points: [], polygonPoints: [], renderToken: 0
    };
    function setHubStatus(text) { try { window.parent.postMessage({ type: 'set-status', text }, '*'); } catch (error) {} }
    function clearHubStatus() { try { window.parent.postMessage({ type: 'clear-status' }, '*'); } catch (error) {} }
    function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
    function getDim() { return parseInt($('max-dimension').value, 10) || 480; }
    function safeName() { return ($('seq-name').value || 'animation-export').trim().replace(/[^a-z0-9-_]+/gi, '-').replace(/-+/g, '-') || 'animation-export'; }
    function loadImage(src) { return new Promise((resolve, reject) => { const img = new Image(); img.onload = () => resolve(img); img.onerror = reject; img.src = src; }); }
    function makeCanvas(dim) { const result = document.createElement('canvas'); result.width = dim; result.height = dim; return result; }
    function canvasToBlob(sourceCanvas) { return new Promise((resolve) => sourceCanvas.toBlob(resolve, 'image/png')); }
    function downloadBlob(blob, filename) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    function hexToRgb(hex) { const parsed = parseInt(hex.replace('#', ''), 16); return { r: (parsed >> 16) & 255, g: (parsed >> 8) & 255, b: parsed & 255 }; }

    let countdownVal = 5, countdownTimer = null, headerLocked = false, headerHovered = false;
    function showCountdown() { els.countdown.textContent = headerLocked ? '🔒' : String(countdownVal); els.countdown.style.borderColor = headerLocked ? 'var(--terracotta-peach)' : 'var(--chiseled-bronze)'; }
    function resetCountdown() { clearInterval(countdownTimer); countdownVal = 5; showCountdown(); }
    function maximizeHeader() { els.topPanel.classList.remove('minimized'); resetCountdown(); }
    function startCountdown() { if (headerLocked || headerHovered) return; clearInterval(countdownTimer); countdownTimer = setInterval(() => { countdownVal -= 1; showCountdown(); if (countdownVal <= 0) { clearInterval(countdownTimer); els.topPanel.classList.add('minimized'); } }, 1000); }
    els.topPanel.addEventListener('mouseenter', () => { headerHovered = true; maximizeHeader(); clearInterval(countdownTimer); });
    els.topPanel.addEventListener('mouseleave', () => { headerHovered = false; resetCountdown(); startCountdown(); });
    els.countdown.addEventListener('dblclick', (event) => { event.preventDefault(); event.stopPropagation(); headerLocked = !headerLocked; showCountdown(); if (headerLocked) { clearInterval(countdownTimer); maximizeHeader(); } else if (!headerHovered) { startCountdown(); } });
    startCountdown();

    $('btn-convert-movie').addEventListener('click', () => els.videoPicker.click());
    els.imagePicker.addEventListener('change', async (event) => {
        const files = [...event.target.files]; if (!files.length) return;
        if (!state.frames.length) $('seq-name').value = files[0].name.replace(/\.[^/.]+$/, '') || 'animation-export';
        for (const file of files) { const source = await fileToDataUrl(file); const img = await loadImage(source); state.frames.push({ id: `${Date.now()}-${Math.random()}`, base64: source, w: img.width, h: img.height, offsetX: 0, offsetY: 0 }); }
        els.imagePicker.value = ''; onFramesChanged();
    });
    function fileToDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
    els.videoPicker.addEventListener('change', async (event) => {
        const file = event.target.files[0]; if (!file) return;
        $('seq-name').value = file.name.replace(/\.[^/.]+$/, '') || 'organon-movie-convert';
        const url = URL.createObjectURL(file); const video = document.createElement('video'); video.src = url; video.muted = true; video.playsInline = true;
        els.viewport.innerHTML = '<div class="loader"></div><p class="help-text">Extracting video frames...</p>'; els.outputCard.hidden = false; setHubStatus('Local Video Extraction Engine Running...');
        try {
            await new Promise((resolve, reject) => { video.onloadedmetadata = resolve; video.onerror = reject; video.load(); });
            const fps = 12, total = Math.max(1, Math.floor(video.duration * fps)); const output = makeCanvas(Math.max(video.videoWidth, video.videoHeight)); output.width = video.videoWidth; output.height = video.videoHeight; const ctx = output.getContext('2d');
            for (let i = 0; i < total; i += 1) { await seekVideo(video, i / fps); ctx.drawImage(video, 0, 0, output.width, output.height); state.frames.push({ id: `${Date.now()}-${Math.random()}`, base64: output.toDataURL('image/jpeg', .85), w: output.width, h: output.height, offsetX: 0, offsetY: 0 }); els.viewport.innerHTML = `<p class="help-text">Extracting video frames (${Math.round(((i + 1) / total) * 100)}%)...</p>`; }
            setHubStatus(`Successfully extracted ${total} frames.`); setTimeout(clearHubStatus, 4000);
        } catch (error) { setHubStatus('Video extraction failed.'); }
        URL.revokeObjectURL(url); els.videoPicker.value = ''; els.outputCard.hidden = true; els.viewport.innerHTML = ''; onFramesChanged();
    });
    function seekVideo(video, seconds) { return new Promise((resolve) => { video.onseeked = () => resolve(); video.currentTime = Math.min(seconds, video.duration || seconds); }); }
    function onFramesChanged() { state.baseFrameIndex = clamp(state.baseFrameIndex, 0, Math.max(0, state.frames.length - 1)); updateOriginalSize(); renderFrameGrid(); updateEstimate(); updateEditorLabels(); els.openEditorBtn.disabled = state.frames.length === 0; els.zipBtn.disabled = state.frames.length === 0; els.compileBtn.disabled = state.frames.length < 2; }
    function updateOriginalSize() { if (!state.frames.length) { $('original-size-label').textContent = ''; return; } const maxW = Math.max(...state.frames.map((frame) => frame.w)), maxH = Math.max(...state.frames.map((frame) => frame.h)); $('original-size-label').textContent = `Original size: ${maxW}×${maxH}`; const max = Math.max(maxW, maxH, 540); $('max-dimension').max = String(max); if (state.frames.length === 1 || parseInt($('max-dimension').value, 10) < Math.max(maxW, maxH)) { $('max-dimension').value = String(Math.max(maxW, maxH)); $('dimension-value').textContent = `${$('max-dimension').value} px`; } }

    let draggedIndex = null;
    function renderFrameGrid() {
        els.frameGrid.innerHTML = ''; els.queueCard.hidden = !state.frames.length; $('frame-skip-container').hidden = state.frames.length <= 15;
        if (state.frames.length <= 15) { $('adj-skip').value = '1'; $('val-skip').textContent = 'Keep All'; }
        state.frames.forEach((frame, index) => {
            const item = document.createElement('div'); item.className = 'frame-thumb-wrapper'; item.draggable = true; item.innerHTML = `<img src="${frame.base64}" alt="Frame ${index + 1}"><span class="frame-index-badge">${index + 1}</span>`;
            if (frame.offsetX || frame.offsetY) item.insertAdjacentHTML('beforeend', `<span class="frame-badge-offset">${frame.offsetX},${frame.offsetY}</span>`);
            item.append(button('thumb-btn frame-preview-btn', '👁', 'Preview processed frame', () => openPreview(index)), button('thumb-btn frame-align-btn', '⊕', 'Align this frame', () => openAlign(index)), button('thumb-btn frame-delete-btn', '×', 'Delete frame', () => { state.frames.splice(index, 1); onFramesChanged(); }));
            item.addEventListener('dragstart', () => { draggedIndex = index; setTimeout(() => item.classList.add('dragging'), 0); }); item.addEventListener('dragend', () => { item.classList.remove('dragging'); draggedIndex = null; });
            item.addEventListener('dragover', (event) => { event.preventDefault(); if (draggedIndex === null || draggedIndex === index) return; const after = event.clientX - item.getBoundingClientRect().left >= item.clientWidth / 2; item.classList.toggle('drag-over-left', !after); item.classList.toggle('drag-over-right', after); });
            item.addEventListener('dragleave', () => item.classList.remove('drag-over-left', 'drag-over-right'));
            item.addEventListener('drop', (event) => { event.preventDefault(); item.classList.remove('drag-over-left', 'drag-over-right'); if (draggedIndex === null || draggedIndex === index) return; const after = event.clientX - item.getBoundingClientRect().left >= item.clientWidth / 2; let target = index + (after ? 1 : 0); const moving = state.frames.splice(draggedIndex, 1)[0]; if (draggedIndex < target) target -= 1; state.frames.splice(target, 0, moving); renderFrameGrid(); });
            els.frameGrid.appendChild(item);
        });
    }
    function button(className, text, title, fn) { const element = document.createElement('button'); element.type = 'button'; element.className = className; element.textContent = text; element.title = title; element.addEventListener('click', (event) => { event.stopPropagation(); fn(); }); return element; }

    const linkedRanges = [['adj-bright','val-bright','%'],['adj-contrast','val-contrast','%'],['adj-exp','val-exp','%'],['adj-sat','val-sat','%'],['adj-tol','val-tol',''],['adj-smooth','val-smooth',''],['frame-delay','delay-value',' ms'],['max-dimension','dimension-value',' px'],['adj-webp-q','val-webp-q','%'],['adj-webp-effort','val-webp-effort','']];
    linkedRanges.forEach(([input, output, suffix]) => $(input).addEventListener('input', () => { $(output).textContent = `${$(input).value}${suffix}`; updateEstimate(); refreshOpenPreviews(); }));
    ['chk-transparent','adj-color','chk-webp-lossless'].forEach((id) => $(id).addEventListener('input', () => { updateEstimate(); refreshOpenPreviews(); }));
    $('adj-skip').addEventListener('input', () => { const value = parseInt($('adj-skip').value, 10); $('val-skip').textContent = value === 1 ? 'Keep All' : `Keep 1 in ${value}`; updateEstimate(); });
    $('opt-format').addEventListener('change', updateFormatPanels);
    function updateFormatPanels() { const webp = $('opt-format').value === 'webp'; $('advanced-webp-card').hidden = !webp; $('webp-overlay').hidden = !webp; $('gif-specific-settings').style.opacity = webp ? '.38' : '1'; $('gif-specific-settings').style.pointerEvents = webp ? 'none' : 'auto'; $('play-btn-text').textContent = webp ? 'PLAY WebP' : 'PLAY GIF'; updateEstimate(); }
    updateFormatPanels();
    function updateEstimate() { if (!state.frames.length) { $('est-size').textContent = 'Est: 0.00 MB'; return; } const count = Math.ceil(state.frames.length / (parseInt($('adj-skip').value, 10) || 1)), dim = getDim(), quality = parseInt($('adj-webp-q').value, 10) / 100; const bpp = $('chk-webp-lossless').checked ? 1.5 : (.2 + quality * .4), bytes = dim * dim * count * bpp / 8; $('est-size').textContent = `Est Size: ~${(bytes / (1024 * 1024)).toFixed(2)} MB`; }

    async function drawPreparedFrame(index, dim) {
        const frame = state.frames[index], output = makeCanvas(dim), ctx = output.getContext('2d', { willReadFrequently: true }); if (!frame) return output;
        const useTrans = $('chk-transparent').checked; if (!useTrans) { ctx.fillStyle = '#000'; ctx.fillRect(0, 0, dim, dim); }
        const image = await loadImage(frame.base64); let w = image.width, h = image.height; if (w > h && w > dim) { h = Math.round(h * dim / w); w = dim; } else if (h >= w && h > dim) { w = Math.round(w * dim / h); h = dim; }
        const x = (dim - w) / 2 + frame.offsetX, y = (dim - h) / 2 + frame.offsetY; ctx.filter = `brightness(${$('adj-exp').value}%) brightness(${$('adj-bright').value}%) contrast(${$('adj-contrast').value}%) saturate(${$('adj-sat').value}%)`; ctx.drawImage(image, x, y, w, h); ctx.filter = 'none'; if (useTrans) applyChroma(ctx, dim); return output;
    }
    function applyChroma(ctx, dim) { const rgb = hexToRgb($('adj-color').value), tol = parseInt($('adj-tol').value, 10), smooth = parseInt($('adj-smooth').value, 10), imageData = ctx.getImageData(0, 0, dim, dim), pixels = imageData.data; for (let i = 0; i < pixels.length; i += 4) { if (!pixels[i + 3]) continue; const distance = Math.hypot(pixels[i] - rgb.r, pixels[i + 1] - rgb.g, pixels[i + 2] - rgb.b); if (distance <= tol) pixels[i + 3] = 0; else if (smooth && distance <= tol + smooth) pixels[i + 3] = Math.floor(pixels[i + 3] * ((distance - tol) / smooth)); } ctx.putImageData(imageData, 0, 0); }
    async function drawOriginalFrame(index, dim) { const output = makeCanvas(dim), frame = state.frames[index]; if (!frame) return output; const image = await loadImage(frame.base64), ctx = output.getContext('2d'); let w = image.width, h = image.height; if (w > h && w > dim) { h = Math.round(h * dim / w); w = dim; } else if (h >= w && h > dim) { w = Math.round(w * dim / h); h = dim; } ctx.drawImage(image, (dim - w) / 2, (dim - h) / 2, w, h); return output; }
    async function renderFrame(index, dim) {
        let output;
        if (state.fixedBaseEnabled && state.movingActions.length && index !== state.baseFrameIndex) { output = await drawPreparedFrame(state.baseFrameIndex, dim); const moving = await drawPreparedFrame(index, dim), mask = buildMask(state.movingActions, dim, 'add', 'subtract'); moving.getContext('2d').globalCompositeOperation = 'destination-in'; moving.getContext('2d').drawImage(mask, 0, 0); output.getContext('2d').drawImage(moving, 0, 0); } else output = await drawPreparedFrame(index, dim);
        if (state.cutoutActions.length) { const cutoutMask = buildMask(state.cutoutActions, dim, 'remove', 'restore'), ctx = output.getContext('2d'); ctx.globalCompositeOperation = 'destination-out'; ctx.drawImage(cutoutMask, 0, 0); ctx.globalCompositeOperation = 'source-over'; }
        applyPaint(output.getContext('2d'), dim); return output;
    }
    function buildMask(actions, dim, positive, negative) { const mask = makeCanvas(dim), ctx = mask.getContext('2d'); actions.forEach((action) => { ctx.save(); ctx.globalCompositeOperation = action.mode === negative ? 'destination-out' : 'source-over'; ctx.fillStyle = '#fff'; ctx.strokeStyle = '#fff'; renderActionPath(ctx, action, dim, true); ctx.restore(); }); return mask; }
    function renderActionPath(ctx, action, dim, fillShape) { const points = action.points.map((point) => ({ x: point.x * dim, y: point.y * dim })); if (!points.length) return; if (action.tool === 'brush') { ctx.lineWidth = Math.max(1, action.size * dim); ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); ctx.moveTo(points[0].x, points[0].y); points.slice(1).forEach((point) => ctx.lineTo(point.x, point.y)); if (points.length === 1) ctx.lineTo(points[0].x + .01, points[0].y); ctx.stroke(); return; } if (action.tool === 'rect' && points.length > 1) { ctx.beginPath(); ctx.rect(points[0].x, points[0].y, points[1].x - points[0].x, points[1].y - points[0].y); if (fillShape) ctx.fill(); else ctx.stroke(); return; } ctx.beginPath(); ctx.moveTo(points[0].x, points[0].y); points.slice(1).forEach((point) => ctx.lineTo(point.x, point.y)); ctx.closePath(); if (fillShape) ctx.fill(); else ctx.stroke(); }
    function applyPaint(ctx, dim) { state.paintActions.forEach((action) => { const layer = makeCanvas(dim), layerCtx = layer.getContext('2d'); layerCtx.strokeStyle = action.color; layerCtx.fillStyle = action.color; layerCtx.lineWidth = Math.max(1, action.size * dim); layerCtx.lineCap = 'round'; layerCtx.lineJoin = 'round'; if (action.softness > 0) layerCtx.filter = `blur(${Math.max(1, action.softness * action.size * dim * .015)}px)`; const points = action.points.map((point) => ({ x: point.x * dim, y: point.y * dim })); if (!points.length) return; layerCtx.beginPath(); layerCtx.moveTo(points[0].x, points[0].y); points.slice(1).forEach((point) => layerCtx.lineTo(point.x, point.y)); if (points.length === 1) layerCtx.lineTo(points[0].x + .01, points[0].y); layerCtx.stroke(); ctx.drawImage(layer, 0, 0); }); }

    async function openPreview(index) { state.currentPreviewIndex = index; els.previewModal.hidden = false; await updateLivePreview(); }
    async function updateLivePreview() { if (state.currentPreviewIndex === null || !state.frames[state.currentPreviewIndex]) return; const result = await renderFrame(state.currentPreviewIndex, 280); els.previewImg.src = result.toDataURL('image/png'); }
    function refreshOpenPreviews() { if (!els.previewModal.hidden) updateLivePreview(); if (!els.editorModal.hidden) renderEditor(); if (!els.alignModal.hidden) renderAlign(); }
    $('btn-play-preview').addEventListener('click', openAnimationPreview);
    async function openAnimationPreview() { if (!state.frames.length) return; els.animModal.hidden = false; els.animLoading.hidden = false; els.animImg.hidden = true; state.animationPlaying = true; const indices = outputIndices(), processed = []; for (const index of indices) { if (!state.animationPlaying) return; processed.push((await renderFrame(index, 280)).toDataURL('image/png')); } els.animLoading.hidden = true; els.animImg.hidden = false; let cursor = 0; clearInterval(state.animationTimer); const tick = () => { if (!state.animationPlaying) return; els.animImg.src = processed[cursor]; cursor = (cursor + 1) % processed.length; }; tick(); state.animationTimer = setInterval(tick, parseInt($('frame-delay').value, 10)); }
    function closeAnimationPreview() { state.animationPlaying = false; clearInterval(state.animationTimer); els.animModal.hidden = true; els.animImg.src = ''; }

    function openAlign(index) { state.alignIndex = index; els.alignModal.hidden = false; renderAlign(); }
    async function renderAlign() { if (!state.frames[state.alignIndex]) { els.alignModal.hidden = true; return; } const frame = state.frames[state.alignIndex]; $('align-frame-number').textContent = `FRAME ${state.alignIndex + 1} / ${state.frames.length}`; $('align-offset').textContent = `X: ${frame.offsetX}  Y: ${frame.offsetY}`; const image = await renderFrame(state.alignIndex, 280); els.alignCanvas.width = image.width; els.alignCanvas.height = image.height; els.alignCanvas.getContext('2d').drawImage(image, 0, 0); }
    $('align-prev').addEventListener('click', () => { state.alignIndex = (state.alignIndex - 1 + state.frames.length) % state.frames.length; renderAlign(); }); $('align-next').addEventListener('click', () => { state.alignIndex = (state.alignIndex + 1) % state.frames.length; renderAlign(); });
    document.querySelectorAll('[data-nudge]').forEach((control) => control.addEventListener('click', () => { const frame = state.frames[state.alignIndex]; if (!frame) return; const direction = control.dataset.nudge; if (direction === 'up') frame.offsetY -= 1; if (direction === 'down') frame.offsetY += 1; if (direction === 'left') frame.offsetX -= 1; if (direction === 'right') frame.offsetX += 1; checkpoint(); renderAlign(); renderFrameGrid(); refreshOpenPreviews(); }));
    $('reset-align').addEventListener('click', () => { const frame = state.frames[state.alignIndex]; if (!frame) return; frame.offsetX = 0; frame.offsetY = 0; checkpoint(); renderAlign(); renderFrameGrid(); refreshOpenPreviews(); });

    els.openEditorBtn.addEventListener('click', () => { if (!state.frames.length) return; state.editorIndex = 0; els.editorModal.hidden = false; edit.finalView = true; resetViewport(); checkpoint(true); updateEditorLabels(); renderEditor(); });
    function updateEditorLabels() { $('editor-frame-number').textContent = `FRAME ${state.editorIndex + 1} / ${Math.max(1, state.frames.length)}`; $('base-frame-label').textContent = `BASE: ${state.baseFrameIndex + 1}`; $('fixed-base-enabled').checked = state.fixedBaseEnabled; }
    $('editor-prev').addEventListener('click', () => switchEditorFrame(-1)); $('editor-next').addEventListener('click', () => switchEditorFrame(1));
    function switchEditorFrame(step) { if (!state.frames.length) return; state.editorIndex = (state.editorIndex + step + state.frames.length) % state.frames.length; updateEditorLabels(); renderEditor(); }
    $('editor-play').addEventListener('click', () => { state.editorPlaying = !state.editorPlaying; $('editor-play').textContent = state.editorPlaying ? '❚❚ PAUSE' : '▶ PLAY'; clearInterval(state.editorTimer); if (state.editorPlaying) state.editorTimer = setInterval(() => switchEditorFrame(1), parseInt($('frame-delay').value, 10)); });
    $('view-final').addEventListener('click', () => setFinalView(true)); $('view-original').addEventListener('click', () => setFinalView(false));
    function setFinalView(finalView) { edit.finalView = finalView; $('view-final').classList.toggle('active', finalView); $('view-original').classList.toggle('active', !finalView); renderEditor(); }
    document.querySelectorAll('#tool-grid [data-tool]').forEach((buttonEl) => buttonEl.addEventListener('click', () => { edit.tool = buttonEl.dataset.tool; document.querySelectorAll('#tool-grid [data-tool]').forEach((item) => item.classList.toggle('active', item === buttonEl)); $('finish-polygon').hidden = edit.tool !== 'polygon' || !edit.polygonPoints.length; }));
    document.querySelectorAll('#target-mode [data-target]').forEach((buttonEl) => buttonEl.addEventListener('click', () => { edit.target = buttonEl.dataset.target; document.querySelectorAll('#target-mode button').forEach((item) => item.classList.toggle('active', item === buttonEl)); $('cutout-panel').hidden = edit.target !== 'cutout'; $('paint-panel').hidden = edit.target !== 'paint'; $('moving-panel').hidden = edit.target !== 'moving'; }));
    bindSegment('#mask-mode button', 'maskMode'); bindSegment('#paint-mode button', 'paintMode'); bindSegment('#moving-mode button', 'movingMode');
    function bindSegment(selector, property) { document.querySelectorAll(selector).forEach((buttonEl) => buttonEl.addEventListener('click', () => { edit[property] = buttonEl.dataset.maskMode || buttonEl.dataset.paintMode || buttonEl.dataset.movingMode; document.querySelectorAll(selector).forEach((item) => item.classList.toggle('active', item === buttonEl)); })); }
    $('brush-size').addEventListener('input', () => { $('brush-size-label').textContent = $('brush-size').value; }); $('brush-softness').addEventListener('input', () => { $('brush-soft-label').textContent = $('brush-softness').value; });
    document.querySelectorAll('#brush-samples [data-brush-size]').forEach((item) => item.addEventListener('click', () => { $('brush-size').value = item.dataset.brushSize; $('brush-size-label').textContent = item.dataset.brushSize; }));
    $('fixed-base-enabled').addEventListener('change', () => { state.fixedBaseEnabled = $('fixed-base-enabled').checked; checkpoint(); renderEditor(); refreshOpenPreviews(); });
    $('base-prev').addEventListener('click', () => moveBase(-1)); $('base-next').addEventListener('click', () => moveBase(1));
    function moveBase(step) { state.baseFrameIndex = (state.baseFrameIndex + step + state.frames.length) % state.frames.length; checkpoint(); updateEditorLabels(); renderEditor(); }
    $('use-current-base').addEventListener('click', () => { state.baseFrameIndex = state.editorIndex; checkpoint(); updateEditorLabels(); renderEditor(); });
    $('clear-cutout').addEventListener('click', () => { state.cutoutActions = []; checkpoint(); renderEditor(); refreshOpenPreviews(); }); $('clear-paint').addEventListener('click', () => { state.paintActions = []; checkpoint(); renderEditor(); refreshOpenPreviews(); }); $('clear-moving').addEventListener('click', () => { state.movingActions = []; checkpoint(); renderEditor(); refreshOpenPreviews(); });
    $('reset-all-edits').addEventListener('click', () => { if (!window.confirm('Clear all cutouts, paint, fixed-base regions and individual alignment changes?')) return; state.cutoutActions = []; state.paintActions = []; state.movingActions = []; state.fixedBaseEnabled = false; state.baseFrameIndex = 0; state.frames.forEach((frame) => { frame.offsetX = 0; frame.offsetY = 0; }); checkpoint(); updateEditorLabels(); renderEditor(); renderFrameGrid(); refreshOpenPreviews(); });
    $('undo-edit').addEventListener('click', undo); $('redo-edit').addEventListener('click', redo);
    function snapshot() { return JSON.stringify({ cutout: state.cutoutActions, paint: state.paintActions, moving: state.movingActions, fixed: state.fixedBaseEnabled, base: state.baseFrameIndex, offsets: state.frames.map(({ offsetX, offsetY }) => ({ offsetX, offsetY })) }); }
    function checkpoint(reset = false) { const value = snapshot(); if (reset || !state.history.length) { state.history = [value]; state.historyIndex = 0; return; } if (state.history[state.historyIndex] === value) return; state.history = state.history.slice(0, state.historyIndex + 1); state.history.push(value); state.historyIndex = state.history.length - 1; }
    function restoreSnapshot(value) { const saved = JSON.parse(value); state.cutoutActions = saved.cutout; state.paintActions = saved.paint; state.movingActions = saved.moving; state.fixedBaseEnabled = saved.fixed; state.baseFrameIndex = saved.base; state.frames.forEach((frame, index) => { if (saved.offsets[index]) { frame.offsetX = saved.offsets[index].offsetX; frame.offsetY = saved.offsets[index].offsetY; } }); updateEditorLabels(); renderEditor(); renderFrameGrid(); refreshOpenPreviews(); }
    function undo() { if (state.historyIndex > 0) { state.historyIndex -= 1; restoreSnapshot(state.history[state.historyIndex]); } } function redo() { if (state.historyIndex < state.history.length - 1) { state.historyIndex += 1; restoreSnapshot(state.history[state.historyIndex]); } }

    async function renderEditor() { if (els.editorModal.hidden || !state.frames[state.editorIndex]) return; const token = ++edit.renderToken, dim = getDim(), result = edit.finalView ? await renderFrame(state.editorIndex, dim) : await drawOriginalFrame(state.editorIndex, dim); if (token !== edit.renderToken) return; els.editorCanvas.width = dim; els.editorCanvas.height = dim; const ctx = els.editorCanvas.getContext('2d'); ctx.clearRect(0, 0, dim, dim); ctx.drawImage(result, 0, 0); drawTransient(ctx, dim); fitCanvas(); }
    function drawTransient(ctx, dim) { const points = edit.tool === 'polygon' ? edit.polygonPoints : edit.points; if (!points.length) return; ctx.save(); ctx.strokeStyle = '#75b2de'; ctx.fillStyle = 'rgba(117,178,222,.18)'; ctx.lineWidth = Math.max(1, dim / 300); ctx.setLineDash([7, 5]); if (edit.tool === 'brush') { ctx.lineWidth = parseInt($('brush-size').value, 10) * dim / Math.max(dim, 480); ctx.lineCap = 'round'; } ctx.beginPath(); ctx.moveTo(points[0].x * dim, points[0].y * dim); points.slice(1).forEach((point) => ctx.lineTo(point.x * dim, point.y * dim)); if (edit.tool === 'rect' && points.length === 2) ctx.rect(points[0].x * dim, points[0].y * dim, (points[1].x - points[0].x) * dim, (points[1].y - points[0].y) * dim); if (edit.tool !== 'brush') { if (edit.tool !== 'lasso' || !edit.drawing) ctx.closePath(); ctx.fill(); } ctx.stroke(); ctx.restore(); }
    function fitCanvas() { const dim = getDim(), area = els.canvasViewport.getBoundingClientRect(), fit = Math.min((area.width - 32) / dim, (area.height - 32) / dim, 1), size = Math.max(40, dim * fit); els.editorCanvas.style.width = `${size}px`; els.editorCanvas.style.height = `${size}px`; els.editorCanvas.style.transform = `translate(${edit.panX}px, ${edit.panY}px) scale(${edit.zoom})`; $('zoom-label').textContent = `${Math.round(edit.zoom * 100)}%`; }
    function resetViewport() { edit.zoom = 1; edit.panX = 0; edit.panY = 0; }
    $('zoom-in').addEventListener('click', () => { edit.zoom = clamp(edit.zoom + .25, .5, 5); fitCanvas(); }); $('zoom-out').addEventListener('click', () => { edit.zoom = clamp(edit.zoom - .25, .5, 5); fitCanvas(); }); $('zoom-fit').addEventListener('click', () => { resetViewport(); fitCanvas(); }); $('zoom-reset').addEventListener('click', () => { resetViewport(); fitCanvas(); }); window.addEventListener('resize', () => { if (!els.editorModal.hidden) fitCanvas(); });
    function pointFromEvent(event) { const rect = els.editorCanvas.getBoundingClientRect(); return { x: clamp((event.clientX - rect.left) / rect.width, 0, 1), y: clamp((event.clientY - rect.top) / rect.height, 0, 1) }; }
    let panStart = null;
    els.editorCanvas.addEventListener('pointerdown', (event) => { if (edit.tool === 'pan') { panStart = { x: event.clientX - edit.panX, y: event.clientY - edit.panY }; els.editorCanvas.setPointerCapture(event.pointerId); return; } if (edit.tool === 'polygon') { edit.polygonPoints.push(pointFromEvent(event)); $('finish-polygon').hidden = false; renderEditor(); return; } edit.drawing = true; edit.points = [pointFromEvent(event)]; els.editorCanvas.setPointerCapture(event.pointerId); renderEditor(); });
    els.editorCanvas.addEventListener('pointermove', (event) => { if (panStart) { edit.panX = event.clientX - panStart.x; edit.panY = event.clientY - panStart.y; fitCanvas(); return; } if (!edit.drawing) return; const point = pointFromEvent(event); if (edit.tool === 'rect') edit.points[1] = point; else edit.points.push(point); renderEditor(); });
    els.editorCanvas.addEventListener('pointerup', (event) => { if (panStart) { panStart = null; return; } if (!edit.drawing) return; edit.drawing = false; if (edit.points.length === 1) edit.points.push(pointFromEvent(event)); commitAction(edit.points); edit.points = []; renderEditor(); });
    els.editorCanvas.addEventListener('dblclick', () => { if (edit.tool === 'polygon') commitPolygon(); }); $('finish-polygon').addEventListener('click', commitPolygon);
    function commitPolygon() { if (edit.polygonPoints.length < 3) return; commitAction(edit.polygonPoints); edit.polygonPoints = []; $('finish-polygon').hidden = true; renderEditor(); }
    function commitAction(points) { if (points.length < 2) return; const action = { tool: edit.tool, points: [...points], size: parseInt($('brush-size').value, 10) / Math.max(1, getDim()), softness: parseInt($('brush-softness').value, 10) / 100 }; if (edit.target === 'moving') { action.mode = edit.movingMode; state.movingActions.push(action); } else if (edit.target === 'paint' && edit.paintMode === 'paint') { action.mode = 'paint'; action.color = $('brush-color').value; state.paintActions.push(action); } else { action.mode = edit.target === 'cutout' ? edit.maskMode : (edit.paintMode === 'erase' ? 'remove' : 'restore'); state.cutoutActions.push(action); } checkpoint(); refreshOpenPreviews(); }

    document.querySelectorAll('[data-close]').forEach((close) => close.addEventListener('click', () => { const id = close.dataset.close; $(id).hidden = true; if (id === 'preview-modal') state.currentPreviewIndex = null; if (id === 'anim-preview-modal') closeAnimationPreview(); if (id === 'frame-editor-modal') { state.editorPlaying = false; clearInterval(state.editorTimer); $('editor-play').textContent = '▶ PLAY'; renderFrameGrid(); refreshOpenPreviews(); } }));
    makeDraggable(els.previewModal, els.previewModal.querySelector('h3')); makeDraggable(els.animModal, els.animModal.querySelector('h3')); makeDraggable(els.alignModal, els.alignModal.querySelector('h3')); makeDraggable(els.editorWindow, $('editor-drag-handle'));
    function makeDraggable(element, handle) { let dragging = false, offsetX = 0, offsetY = 0; handle.addEventListener('pointerdown', (event) => { if (window.innerWidth <= 680 || event.target.closest('button')) return; dragging = true; const rect = element.getBoundingClientRect(); offsetX = event.clientX - rect.left; offsetY = event.clientY - rect.top; handle.setPointerCapture(event.pointerId); }); handle.addEventListener('pointermove', (event) => { if (!dragging) return; element.style.position = 'fixed'; element.style.left = `${event.clientX - offsetX}px`; element.style.top = `${event.clientY - offsetY}px`; element.style.right = 'auto'; element.style.transform = 'none'; }); handle.addEventListener('pointerup', () => { dragging = false; }); }

    function outputIndices() { const skip = parseInt($('adj-skip').value, 10) || 1; let indices = state.frames.map((_, index) => index).filter((_, index) => index % skip === 0); if ($('chk-reverse').checked) indices.reverse(); if ($('chk-forverse').checked) indices = indices.concat([...indices].reverse()); return indices; }
    els.zipBtn.addEventListener('click', async () => { if (!state.frames.length || typeof JSZip === 'undefined') return; els.zipBtn.disabled = true; els.zipBtn.textContent = 'PACKAGING FRAMES...'; setHubStatus('Rendering processed PNG frames into ZIP package...'); try { const zip = new JSZip(), folder = zip.folder(`${safeName()}-frames`), digits = String(state.frames.length).length; for (let index = 0; index < state.frames.length; index += 1) { const rendered = await renderFrame(index, getDim()), blob = await canvasToBlob(rendered); folder.file(`${safeName()}-frame-${String(index + 1).padStart(Math.max(3, digits), '0')}.png`, blob); } const archive = await zip.generateAsync({ type: 'blob' }); downloadBlob(archive, `${safeName()}-frames.zip`); setHubStatus('Processed PNG frames downloaded as ZIP.'); setTimeout(clearHubStatus, 4000); } catch (error) { setHubStatus(`Frame ZIP failed: ${error.message}`); } els.zipBtn.disabled = false; els.zipBtn.textContent = 'DOWNLOAD FRAMES ZIP'; });
    els.compileBtn.addEventListener('click', async () => { if (state.frames.length < 2) return; els.compileBtn.disabled = true; els.compileBtn.textContent = 'PROCESSING...'; els.outputCard.hidden = false; els.viewport.innerHTML = '<div class="loader"></div>'; const indices = outputIndices(), images = []; setHubStatus('Synthesizing processed frame array...'); try { for (const index of indices) images.push((await renderFrame(index, getDim())).toDataURL('image/png')); if ($('opt-format').value === 'webp') setHubStatus('Animated WebP muxing is unavailable in this browser build. Exporting GIF instead.'); const lossy = $('opt-lossy').value, sampleInterval = lossy === 'high' ? 30 : lossy === 'low' ? 20 : 10; gifshot.createGIF({ images, interval: parseInt($('frame-delay').value, 10) / 1000, gifWidth: getDim(), gifHeight: getDim(), sampleInterval, numWorkers: 2 }, (result) => { els.compileBtn.disabled = false; els.compileBtn.textContent = 'MAKE & SAVE ANIMATION'; if (result.error) { els.viewport.innerHTML = '<p class="help-text">ENGINE FAILURE: Unable to compile.</p>'; setHubStatus('Compilation engine failure.'); return; } els.viewport.innerHTML = `<img src="${result.image}" alt="Compiled animation">`; els.downloadAnchor.href = result.image; els.downloadAnchor.download = `${safeName()}.gif`; els.downloadAnchor.click(); setHubStatus('Animation generated and downloaded.'); setTimeout(clearHubStatus, 4000); }); } catch (error) { els.compileBtn.disabled = false; els.compileBtn.textContent = 'MAKE & SAVE ANIMATION'; els.viewport.innerHTML = `<p class="help-text">ERROR: ${error.message}</p>`; setHubStatus('Compilation engine failure.'); } });
    onFramesChanged();
})();
