(() => {
  'use strict';
  const api=window.AdvancedAnimationMaker;
  if(!api)return;
  const $=(id)=>document.getElementById(id),{ui,state,clamp}=api,encoder=new TextEncoder();
  api.stopPreview=()=>{state.previewToken+=1;if(state.previewTimer)window.clearTimeout(state.previewTimer);state.previewTimer=null;};
  api.previewOutput=async()=>{api.stopPreview();const token=++state.previewToken,frames=await api.outputFrames();if(!frames.length)return api.notify('Load image frames first.');ui.animModal.hidden=false;ui.animLoading.hidden=true;ui.animImage.hidden=false;let index=0;const delay=api.frameDelay(frames.length),tick=()=>{if(token!==state.previewToken||ui.animModal.hidden)return;ui.animImage.src=frames[index].toDataURL('image/png');index=(index+1)%frames.length;state.previewTimer=window.setTimeout(tick,delay);};tick();api.showOutput(frames[0]);};
  const fourCC=(text)=>encoder.encode(text),u16=(value)=>new Uint8Array([value&255,(value>>>8)&255]),u24=(value)=>new Uint8Array([value&255,(value>>>8)&255,(value>>>16)&255]),u32=(value)=>new Uint8Array([value&255,(value>>>8)&255,(value>>>16)&255,(value>>>24)&255]);
  const join=(parts)=>{const length=parts.reduce((total,item)=>total+item.length,0),result=new Uint8Array(length);let offset=0;parts.forEach((item)=>{result.set(item,offset);offset+=item.length;});return result;};
  const chunk=(name,payload)=>join([fourCC(name),u32(payload.length),payload,payload.length%2?new Uint8Array([0]):new Uint8Array()]);
  const fourAt=(bytes,offset)=>String.fromCharCode(bytes[offset],bytes[offset+1],bytes[offset+2],bytes[offset+3]);
  const uintAt=(bytes,offset)=>(bytes[offset]|(bytes[offset+1]<<8)|(bytes[offset+2]<<16)|(bytes[offset+3]<<24))>>>0;
  const webpPayload=async(canvas,quality)=>{const blob=await new Promise((resolve)=>canvas.toBlob(resolve,'image/webp',quality));if(!blob||blob.type!=='image/webp')throw new Error('This browser cannot encode WebP.');const bytes=new Uint8Array(await blob.arrayBuffer());if(fourAt(bytes,0)!=='RIFF'||fourAt(bytes,8)!=='WEBP')throw new Error('Invalid WebP frame data.');const chunks=[];let offset=12;while(offset+8<=bytes.length){const name=fourAt(bytes,offset),size=uintAt(bytes,offset+4),end=offset+8+size;chunks.push({name,raw:bytes.slice(offset,end+size%2)});offset=end+size%2;}const imageChunks=chunks.filter((entry)=>['ALPH','VP8 ','VP8L'].includes(entry.name));return{bytes:join(imageChunks.map((entry)=>entry.raw)),alpha:imageChunks.some((entry)=>entry.name==='ALPH'||entry.name==='VP8L')};};
  const animatedWebP=async(frames,delay)=>{const width=frames[0].width,height=frames[0].height,quality=$('chk-webp-lossless')?.checked?1:Number($('adj-webp-q')?.value||80)/100,encoded=[];let alpha=false;for(const frame of frames){const entry=await webpPayload(frame,quality);encoded.push(entry);alpha||=entry.alpha;}const header=new Uint8Array(10);header[0]=0x02|(alpha?0x10:0);header.set(u24(width-1),4);header.set(u24(height-1),7);const animation=join([new Uint8Array([0,0,0,0]),u16(clamp(Number($('play-count')?.value||0),0,65535))]);const sequence=encoded.map((entry)=>chunk('ANMF',join([u24(0),u24(0),u24(width-1),u24(height-1),u24(clamp(delay,11,0xFFFFFF)),new Uint8Array([0x02]),entry.bytes])));const payload=join([fourCC('WEBP'),chunk('VP8X',header),chunk('ANIM',animation),...sequence]);return new Blob([join([fourCC('RIFF'),u32(payload.length),payload])],{type:'image/webp'});};
  const save=(blob,filename)=>{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000);};
  api.exportOutput=async(forceZip=false)=>{api.stopPreview();const frames=await api.outputFrames();if(!frames.length)return api.notify('Load image frames first.');api.showOutput(frames[0]);const format=forceZip?'zip':($('opt-format')?.value||'gif'),delay=api.frameDelay(frames.length);try{if(format==='zip'){if(!window.JSZip)throw new Error('ZIP support is unavailable.');const zip=new JSZip(),folder=zip.folder(`${api.exportName()}-frames`),digits=Math.max(3,String(frames.length).length);for(let index=0;index<frames.length;index+=1){const blob=await new Promise((resolve)=>frames[index].toBlob(resolve,'image/png'));folder.file(`frame-${String(index+1).padStart(digits,'0')}.png`,blob);}save(await zip.generateAsync({type:'blob'}),`${api.exportName()}-frames.zip`);api.notify('PNG frame ZIP saved.');return;}if(format==='webp'){save(await animatedWebP(frames,delay),`${api.exportName()}.webp`);api.notify('Animated WebP saved.');return;}if(!window.gifshot)throw new Error('GIF support is unavailable.');window.gifshot.createGIF({images:frames.map((frame)=>frame.toDataURL('image/png')),interval:delay/1000,gifWidth:frames[0].width,gifHeight:frames[0].height,numWorkers:2,sampleInterval:10},(result)=>{if(result.error){api.notify('GIF export failed.');return;}const binary=atob(result.image.split(',')[1]),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index+=1)bytes[index]=binary.charCodeAt(index);save(new Blob([bytes],{type:'image/gif'}),`${api.exportName()}.gif`);api.notify('GIF saved.');});}catch(error){api.notify(`Export error: ${error.message}`);}};
})();